---
- hosts: all
  gather_facts: true
  become: True
  become_method: sudo

  tasks:

  - name: Fix PermitRoot in /etc/ssh/sshd_config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin *es$'
      replace: 'PermitRootLogin no'

  - name: Restart Service 
    ansible.builtin.service:
      name: sshd
      state: restarted 
