---
- hosts: all
  become: true
  gather_facts: True

  vars:
    package: vmware-vra-software-agent-service

  tasks:
    - name: look for VMware vra package 
      shell: rpm -qi {{ package }}
      register: result 
      ignore_errors: True

    - debug: msg="{{ result.rc }}"
      when:  result.rc == 1

    - name: stop VRA service 
      shell: systemctl stop vmware-vra-software-agent-service
      when: result.rc == 0
      ignore_errors: True

    - name: disable VRA servive
      shell: systemctl disable vmware-vra-software-agent-service
      when: result.rc == 0
      ignore_errors: True

    - name: remove VRA package
      shell:  rpm -e vmware-vra-software-agent-service
      when: result.rc == 0
      ignore_errors: True

    - name: Look for /opt/vmware-appdirector directory
      stat:
        path: /opt/vmware-appdirector
      register: appdirector

    - name:  Remove directory /opt/vmware-appdirector when it exists
      file:
        path: /opt/vmware-appdirector/
        state: absent

    - name: check for /usr/lib/vmware-tools/lib64/libcrypto.so.0.9.8/libcrypto.so.0.9.8
      stat:
        path: /usr/lib/vmware-tools/lib64/libcrypto.so.0.9.8/libcrypto.so.0.9.8
      register:  lib_file

    - name:  remove /usr/lib/vmware-tools/lib64/libcrypto.so.0.9.8/libcrypto.so.0.9.8
      file:
        path: /usr/lib/vmware-tools/lib64/libcrypto.so.0.9.8/libcrypto.so.0.9.8
        state: absent
      when: lib_file.stat.exists

    - name: reload systemd
      shell: systemctl daemon-reload

    - name: reset systemd so it won;t complain about the missinh serice
      shell: systemctl reset-failed
